#1.
# name = input("Enter your full name : ")
# a = name.split()
# print(a[0])


#2.
# city = input("Enter your city name : ")
# print(city.upper())
# print(city.lower())
# print(city.title())


#3.
# string = "Technology"
# print(string[::-1])


#4.
# a = "Data"
# b = "Science"
# print(a + "/" +b)
# print(a,"/",b)


##5.
# price = float(input("Enter the product price : "))
# print(f"price of the product{price:.2f}")



#6.
# name = "dilli"
# age = 25
# print(f"Hello {name} , Your {age} years old")


#7.
# sentence = "Python is awesome"
# a = "Python" in sentence
# print(a)

#8.
# sentence = input("Enter your sentence : ")
# print(len(sentence))


#9.
# product_price = 200
# tax = (product_price*0.05)
# print(f"Final price of he product after tax is : Rs.{product_price+tax}/-")


#10.
# name = "alice"
# b = "i" in name
# c = "z" is not name
# print(b)
# print(c)


#11.
# a = 65
# b = 98
# c = 32
# sum = (a+b+c)
# average = (sum/3)
# print(f"The average of three product score is : {average}")


#12.
# weight  = int(input('Enter your weight in kgs : '))
# height = float(input("enter your height in meters : "))
# bmi = (weight/height**2)
# print(f"Your body mass index is : {bmi}")


#13.
# string = "I Love python"
# print(string[2:6])


#14.
sentence = "This is a bad idea"
print(sentence.replace("bad","good"))

#15.
a = 1000
b = 1000
c = a is b
print(c)